version: '3.7'

services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=movie
      - MYSQL_PASSWORD=movie-pass
      - MYSQL_DATABASE=movie-db
    networks:
      - database_net
    volumes:
      - database_data:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password
    ports:
      - "3306:3306"

  adminer:
    image: dehy/adminer:latest
    networks:
      - database_net
    ports:
      - "8080:80"

networks:
  database_net:
    driver: bridge

volumes:
  database_data: